-- Anti-triche et sanctions du classé (à lancer une fois dans Supabase : SQL
-- Editor > New query > Run). Sans risque si relancé.

-- Match classé invalidé par l'anti-triche (somme des temps saisis
-- supérieure au temps écoulé depuis l'affichage de la saisie, cf.
-- api/_lib/sanctions.js) : temps passé à saisir et somme des temps, en
-- secondes. Visible des administrateurs seulement (section Litiges).
alter table match_history add column if not exists triche boolean not null default false;
alter table match_history add column if not exists duree_saisie integer;
alter table match_history add column if not exists somme_temps integer;

-- Sanctions décidées par un administrateur : ban du mode classé d'une
-- semaine, jusqu'à la fin de la saison, définitif (fin null), ou aucune
-- conséquence (gardée pour l'historique de modération).
create table if not exists sanctions (
  id bigint generated by default as identity primary key,
  discord_id text not null,
  type text not null,
  fin timestamptz,
  match_id bigint,
  admin text,
  created_at timestamptz not null default now()
);

create index if not exists sanctions_joueur on sanctions (discord_id);

-- Fermée à l'accès public (le site passe par la clé de service).
alter table sanctions enable row level security;
