-- Légendes locales tuées (à lancer une fois dans Supabase : SQL Editor > New
-- query > Run). Sans risque si relancé.

-- Une ligne par joueur qui a tué une légende locale (cf.
-- api/_lib/legendes.js) : temps saisi à la fin d'un match (pas un abandon,
-- litige compris), ou temps du lanceur d'un entraînement. Les légendes
-- "une fois par jour" (type legende_locale_jour de DB/boss.json) tuées
-- depuis le dernier reset (4 h, heure de Paris) ne sont plus tirées pour
-- ce joueur ni pour ses adversaires (chacun a son propre monde).
create table if not exists legendes_tuees (
  id bigint generated by default as identity primary key,
  discord_id text not null,
  boss_id text not null,
  match_id bigint,
  temps_secondes integer,
  entrainement boolean not null default false,
  tuee_le timestamptz not null default now(),
  -- Une seule mort par joueur et par match (temps corrigé en entraînement).
  unique (match_id, discord_id)
);

create index if not exists legendes_tuees_joueur on legendes_tuees (discord_id, tuee_le);

-- Fermée à l'accès public (le site passe par la clé de service).
alter table legendes_tuees enable row level security;
