-- Litiges (à lancer une fois dans Supabase : SQL Editor > New query > Run).
-- Sans risque si relancé.

-- Identifiant et date des matchs : nécessaires pour corriger un litige
-- (déjà présents si la table a été créée avec).
alter table match_history add column if not exists id bigint generated by default as identity;
alter table match_history add column if not exists created_at timestamptz not null default now();

-- Manche contestée par un joueur (cf. api/rooms/[room_id]/[action].js) :
--   litige     : null (match normal), 'ouvert' (invalidé, visible des
--                administrateurs seulement) ou 'republie' (temps corrigés
--                par un administrateur, match public)
--   litige_par : 'j1' | 'j2', joueur qui a signalé le litige (gardé après
--                republication, pour la modération)
--   republie_par / republie_le : administrateur qui a republié le match
alter table match_history add column if not exists litige text;
alter table match_history add column if not exists litige_par text;
alter table match_history add column if not exists republie_par text;
alter table match_history add column if not exists republie_le timestamptz;

create index if not exists match_history_litiges
  on match_history (litige)
  where litige is not null;
