-- Signalements de matchs (à lancer une fois dans Supabase : SQL Editor >
-- New query > Run). Sans risque si relancé.
--
-- Tout joueur connecté (sauf pendant un ban du classé) peut signaler un
-- match terminé depuis la page Historique, avec une raison obligatoire (500
-- caractères au plus) : une fois par match, 10 par jour au plus (reset à
-- 4 h, heure de Paris). Rien ne change pour les autres joueurs tant qu'un
-- administrateur ou mini admin n'a pas traité le signalement (cf.
-- api/matches.js) :
--   statut : 'ouvert' (à traiter), 'sans_suite', 'corrige' (temps corrigés,
--            match toujours valide) ou 'invalide' (match invalidé,
--            match_history.litige = 'invalide')
--   traite_par / traite_le : administrateur qui a traité le signalement
create table if not exists signalements (
  id bigint generated by default as identity primary key,
  match_id bigint not null,
  discord_id text not null,
  commentaire text not null,
  statut text not null default 'ouvert',
  traite_par text,
  traite_le timestamptz,
  created_at timestamptz not null default now(),
  unique (match_id, discord_id)
);

create index if not exists signalements_ouverts on signalements (match_id) where statut = 'ouvert';
create index if not exists signalements_joueur on signalements (discord_id, created_at);

-- Fermée à l'accès public (le site passe par la clé de service).
alter table signalements enable row level security;
