-- Mode Random world boss (à lancer une fois dans Supabase : SQL Editor >
-- New query > Run). Sans risque si relancé. Cf. api/_lib/world_boss.js.
-- Prérequis : sql/equipes.sql (colonne rooms.membres).

-- Une ligne par partie terminée : boss, réussite ou échec, joueurs et
-- persos tirés (qui a joué quel perso, sa constellation et son niveau).
create table if not exists world_boss_history (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  boss_id text not null,
  reussite boolean not null,
  createur text,
  -- [{ discord_id, nom, avatar }]
  membres jsonb not null default '[]',
  -- [{ perso_id, element, joue_par, constellation, niveau }]
  persos jsonb not null default '[]',
  saison integer
);

-- Légende locale réussie : joueur hôte du monde (elle est tuée pour lui,
-- cf. table legendes_tuees).
alter table world_boss_history add column if not exists hote text;

create index if not exists world_boss_history_date on world_boss_history (created_at desc);

-- Fermée à l'accès public (le site passe par la clé de service).
alter table world_boss_history enable row level security;
